import {
    assert,
    assertEquals,
    assertFalse,
    assertNotEquals,
} from "./asserts.test.ts";
import { Dimensions } from "./dimensions.ts";
import { Quantity } from "./quantity.ts";

Deno.test("Quantity instance equality", async (t) => {
    /**
     * Equality test helper.
     * Given two functions that create Quantities, make sure that the Quantities
     * generated by the first function are equal to themsevles, but not equal to
     * the Quantity generated by the second.
     */
    const check = (
        description: string,
        factory: () => Quantity,
        other: () => Quantity,
    ) => {
        const q1a = factory();
        const q1b = factory();
        const q2 = other();
        return t.step(description, () => {
            assert(q1a.equals(q1b));
            assertFalse(q1a.equals(q2));
            assertFalse(q2.equals(q1b));
            // Also check that the built-in deep equals agrees:
            assertEquals(q1a, q1b);
            assertNotEquals(q1a, q2);
        });
    };

    // The first number should equal itself but not equal the second:
    await check(
        "dimensionless number",
        () => new Quantity(15),
        () => new Quantity(12),
    );
    await check(
        "negative dim'less number",
        () => new Quantity(-50),
        () => new Quantity(12),
    );
    await check(
        "Zero",
        () => new Quantity(0),
        () => new Quantity(1),
    );
    await check(
        "Different dimensions, same magnitude",
        // This one will equal itself:
        () =>
            new Quantity(15, {
                dimensions: new Dimensions([1, 0, 0, 0, 0, 0, 0, 0]),
            }),
        // But the one above won't equal this one, with different dimensions:
        () =>
            new Quantity(15, {
                dimensions: new Dimensions([0, 1, 0, 0, 0, 0, 0, 0]),
            }),
    );
    await check(
        "Different dimensions, same magnitude (2)",
        () =>
            new Quantity(0, {
                dimensions: new Dimensions([1, 0, 0, 0, 0, 0, 0, 0]),
            }),
        () =>
            new Quantity(0, {
                dimensions: new Dimensions([0, 0, 0, 0, 0, 0, 0, 0]),
            }),
    );
    await check(
        "Different dimensions, same magnitude (3)",
        () =>
            new Quantity(-10, {
                dimensions: new Dimensions([1, 0, 0, 1, 2, 0, 0, 0]),
            }),
        () =>
            new Quantity(-10, {
                dimensions: new Dimensions([1, 0, 0, 1, 1, 0, 0, 0]),
            }),
    );
    await check(
        "Different custom dimensions, same magnitude and regular dimensions",
        () =>
            new Quantity(-10, {
                // deno-fmt-ignore
                dimensions: new Dimensions([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1], ["a", "b", "c", "d"]),
            }),
        () =>
            new Quantity(-10, {
                dimensions: new Dimensions(
                    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                    ["a", "b", "c", "d"],
                ),
            }),
    );
    await check(
        "Different custom dimension names, same magnitude and dimension values",
        () =>
            new Quantity(-10, {
                dimensions: new Dimensions(
                    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
                    ["a", "b", "c", "d"],
                ),
            }),
        () =>
            new Quantity(-10, {
                dimensions: new Dimensions(
                    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2],
                    ["a", "b", "c", "elf"],
                ),
            }),
    );
});
